name: flutter_boilerplate
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info: ^0.0.3
  url_launcher: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  # 使用 MD 的 icon 和 font
  uses-material-design: true

  # 静态资源
  assets:
    # @1x
    - assets/images/
    - assets/icons/
    # @2x
    - assets/images/2.0x/
    - assets/icons/2.0x/
    # @3x
    - assets/images/3.0x/
    - assets/icons/3.0x/


  # 自定义字体
  fonts:
     - family: Source Han Sans
       fonts:
         - asset: assets/fonts/SourceHanSansCN-ExtraLight.otf
         - asset: assets/fonts/SourceHanSansCN-Light.otf
         - asset: assets/fonts/SourceHanSansCN-Normal.otf
         - asset: assets/fonts/SourceHanSansCN-Regular.otf
         - asset: assets/fonts/SourceHanSansCN-Medium.otf
         - asset: assets/fonts/SourceHanSansCN-Bold.otf
         - asset: assets/fonts/SourceHanSansCN-Heavy.otf
     - family: Iconfont
       fonts:
         - asset: assets/fonts/iconfont.ttf

